config/routes.rb
SubmissionApp::Application.routes.draw do
  # get "groups/show"

  # get "group/show"

  resource :sessions, :only => [:new, :create, :destroy]

  resources :courses, :only => [:new, :create, :index, :show, :destroy] do
    resources :users, :only => [:new, :create]
    resources :student_enrollments, :only => [:create, :destroy]
  end

  resources :users, :only => [:show, :index, :destroy]

  resources :group_types do
    resources :assignments, :only => [:new]
    resources :groups, :only => [:create]
    post 'csv', :to => 'group_types#edit_by_csv', :as => 'edit_by_csv'
  end

  resources :groups, :only => [:show]

  resources :assignments, :only => [:show, :create, :destroy, :edit, :update] do
    resources :assignment_submissions, :except => [:update, :edit] do
      resources :comments, :only => [:create, :destroy]
      post 'finalize', :to => 'assignment_submissions#finalize',
                       :as => "finalize"
      get 'printable', :to => 'assignment_submissions#printable',
                        :as => "printable"
      get 'pdf', :to => 'assignment_submissions#pdf',
                 :as => 'pdf'
    end

    get 'groups/:id', :to => 'groups#assignment_show', :as => 'group_show'
    get 'groups/:id/zip', :to => 'groups#assignment_zip', :as => 'group_zip'


    get 'cycles', :to => 'peer_review_cycles#index', :as => "cycles"
    post 'cycles', :to => 'peer_review_cycles#create'
    put 'cycles/:id/edit', :to => 'peer_review_cycles#update'
    delete 'cycles/:id', :to => 'peer_review_cycles#delete', :as => "cycles_delete"
    get 'cycles/:id/edit', :to => 'peer_review_cycles#edit', :as => "cycles_edit"
    post 'cycles/:id/activate', :to => 'peer_review_cycles#activate',
                                :as => "cycle_activate"
    post 'cycles/:id/deactivate', :to => 'peer_review_cycles#deactivate',
                                :as => "cycle_deactivate"

    resources :marking_categories, :only => [:create, :destroy, :update, :index]
    resources :custom_behaviors, :only => [:create, :destroy, :update, :index]

    resources :extensions, :only => [:index, :create]
  end

  resources :extensions, :only => [:destroy]

  resources :notifications, :only => [:destroy, :index]

  get 'assignments/:id/marks.csv', :to => 'assignments#get_csv',
                                   :as => 'assignment_marks'

  get 'assignments/:id/submissions.zip', :to => 'assignments#get_zipfile',
                                         :as => 'assignment_zipfile'

  post 'assignments/:id/peer_review', :to => 'assignments#peer_review',
                                      :as => 'assignment_peer_review'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/file.zip',
                                    :to => 'assignment_submissions#get_zip',
                                    :as => 'assignment_submission_zip'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/Main.hs',
                                    :to => 'assignment_submissions#download_raw',
                                    :as => 'assignment_submission_raw'

  get 'comment_files/:id', :to => 'comments#get_file',
                           :as => 'comment_file'

  root :to => 'courses#index'

  get 'admin/log', :to => 'admin#log'
  get 'admin/summary_log', :to => 'admin#summary_log'
  get 'admin/database', :to => 'admin#database'
  get 'admin/spoof-login/:id', :to => 'admin#spoof_login'
  get 'admin/charts', :to => 'admin#charts'

  get 'files/:id', :to => 'submission_files#serve', :as => 'file_serve'
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :info, :name, :group_type, :group_type_id, :due_date,
                   :submission_format,
                   :is_due_date_compulsary, :filepath_regex,
                   :is_visible, :submission_instructions, :visible_comments

  belongs_to :group_type
  has_many :groups, :through => :group_type, :source => :groups

  has_many :submissions, :class_name => "AssignmentSubmission"
  # TODO submissions should have timestamps
  has_many :students_who_have_submitted, :through => :submissions, :source => :user
  has_many :submission_permissions, :through => :submissions,
                                    :source => :submission_permissions,
                                    :dependent => :destroy

  has_many :comments, :through => :submissions, :source => :comments

  has_many :courses, :through => :group_type, :source => :courses
  has_many :conveners, :through => :courses, :source => :convener

  has_many :students, :through => :groups, :source => :students
  has_many :staff, :through => :groups, :source => :staff

  validates :info, :name, :group_type_id, :submission_format,
           :presence => true

  validate :name_is_acceptable

  has_many :marking_categories, :dependent => :destroy

  has_many :peer_review_cycles, :dependent => :destroy

  has_many :extensions

  has_many :custom_behaviors

  after_create :make_directory, :send_notifications

  extend FriendlyId

  friendly_id :name, :use => :slugged

  def self.visible
    self.where(:is_visible => true)
  end

  def name_is_acceptable
    unless self.name.match /\A[a-zA-Z:_0-9 ]+\Z/
      self.errors[:name] << "The name must match this regex: /\A[a-zA-Z:0-9 ]+\Z/. " +
                       "That is to say, it may only have letters, numbers, colons and spaces."
    end
  end

  def relevant_submissions(user)
    case user.relationship_to_assignment(self)
    when :student
      self.submissions.find_by_user_id_and_assignment_id(user.id, self.id)

    # TODO: Use SQl.
    when :staff
      # user.staffed_groups.where(:group_type_id => self.group_type_id)
      #           .map{ |x| x.students }
      #           .flatten
      #           .map{ |x| x.most_recent_submission(self) }
      #           .select{ |x| x }
      self.submissions
    when :convener
      self.submissions
      # out = self.students.map{ |x| x.most_recent_submission(self) }
      #                    .select{ |x| x }
    end
  end

  def sanitize(filename)
    filename.strip!
    filename.gsub!(/^.*(\\|\/)/, '') # remove slashes etc
    filename.gsub!(/[^0-9A-Za-z.\-]/, '_') # remove non-ascii
    return filename
  end

  def path
    "#{Rails.root.to_s}/upload/#{self.id}"
  end

  def path_without_upload
    "#{sanitize(self.name)}"
  end

  def update_zip
    system("cd #{self.path} && zip -r #{sanitize(self.name)}.zip *")
  end

  def zip_path
    "#{self.path}/#{self.name}.zip"
  end

  def make_directory
    Dir.mkdir(self.path) unless File.directory?(self.path)
  end

  #TODO: Add "marker" as a field here.
  def marks_csv
    marking_category_names = self.marking_categories.map(&:name)

    first_line = ["name", "uni id", "submission time"] + marking_category_names


    peer_review_cycles.each do |cycle|
      if cycle.maximum_mark
        first_line << "Peer review cycle id #{cycle.id}"
      end
    end

    out = [first_line.join(",")]

    self.students.each do |student|
      most_recent_submission = student.most_recent_submission(self)
      submission_time = most_recent_submission.created_at rescue ""
      marks = []
      self.marking_categories.each do |category|
        marks << category.mark_for_submission(most_recent_submission) rescue ""
      end
      peer_review_cycles.each do |cycle|
        if cycle.maximum_mark
          marks << cycle.mark_for_submission(most_recent_submission) rescue ""
        end
      end
      out << "#{student.name},#{student.uni_id},#{submission_time},#{marks.join(",")}"
    end
    out.join("\n")
  end

  # Does the assignment have a due date in the past?
  # If it doesn't have a due date, it's never overdue.
  # If the due date isn't compulsary, it's never overdue
  # If the user has an extension, we use that date instead.
  def already_due(user)
    return false if user.is_admin_or_convener?

    extension = Extension.find_by_user_id_and_assignment_id(user.id, self.id)
    if extension
      return extension.due_date < Time.zone.now
    end

    self.due_date && self.is_due_date_compulsary && self.due_date < Time.zone.now
  end

  def add_marking_category!(hash)
    category = MarkingCategory.new(hash)
    category.assignment_id = self.id
    category.save!
  end

  def create_marking_scheme(scheme)
    scheme.each do |hash|
      self.add_marking_category!(hash)
    end
  end

  def replace_marking_scheme(scheme)
    self.marking_categories.each(&:destroy)
    create_marking_scheme(scheme)
  end

  def maximum_mark
    self.marking_categories.map{|x| x.maximum_mark}.sum
  end

  def disable_submitting_until_comment(user)
    self.peer_review_cycles.any? { | cycle | cycle.disable_submissions(user) }
  end

  def conveners_and_staff
    self.conveners + self.staff
  end

  def send_notifications
    Notification.create!((self.students + self.staff).map do |u|
      {:user_id => u.id, :notable_id => self.id, :notable_type => "Assignment"}
    end)
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_filter :require_logged_in
  before_filter :require_permission, :only => [:edit, :update, :destroy,
                                          :get_csv, :get_zipfile, :peer_review]
  before_filter :require_convener_or_admin, :only => [:new, :create]

  def require_permission
    @assignment = Assignment.find(params[:id])
    #unless @assignment.group_type.conveners.include?(current_user) || current_user.is_admin
    unless @assignment.conveners_and_staff.include?(current_user) || current_user.is_admin
      flash[:errors] = ["You don't have permission to do that with assignments."]
      redirect_to @assignment
    end
  end

  def new
    @group_type_id = params[:group_type_id]
    @group_type = GroupType.find(params[:group_type_id])

    if current_user.is_admin_or_convener?
      @assignment = Assignment.new
      @assignment.group_type = @group_type
      render :new
    else
      flash[:errors] = ["You can't create assignments for that course."]
      redirect_to courses_url
    end
  end

  def create
    @assignment = Assignment.new(params[:assignment])
    if @assignment.save
      redirect_to @assignment
    else
      flash.now[:errors] = @assignment.errors.full_messages
      render :new
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
    render :edit
  end

  def update
    @assignment.update_attributes(params[:assignment])
    if @assignment.save
      redirect_to @assignment
    else
      flash[:errors] = @assignment.errors.full_messages
      redirect_to edit_assignment_url(@assignment)
    end
  end

  def show
    @assignment = Assignment.find(params[:id])
    @relation = current_user.relationship_to_assignment(@assignment)

    current_user.notifications.where(:notable_type => "Assignment",
                                     :notable_id => @assignment.id).delete_all

    unless @relation == :student
      @number_submitted = @assignment.submissions
                                     .group(:user_id).count.count
      @number_finalized = @assignment.submissions
                                            .where(:is_finalized => true)
                                            .group(:user_id).count.count
      @number_students = @assignment.students.count
    end

    case @relation
    when :student
      if @assignment.is_visible
        @user_submissions = @assignment.submissions
                                       .where(:user_id => current_user.id)
                                       .order('created_at DESC')
        @permitted_submissions = current_user.permitted_submissions_for_assignment(@assignment)
        render :show_to_student
      else
        flash[:errors] = ["That assignment isn't visible yet"]
        redirect_to :back
      end
    when :staff

      @submissions = @assignment.relevant_submissions(current_user)

      render :show_to_staff
    when :convener
      @submissions = @assignment.relevant_submissions(current_user)
      render :show_to_staff
    else
      if current_user.is_admin
        @submissions = @assignment.submissions
        render :show_to_staff
      else
        redirect_to "/"
      end
    end
  end

  def destroy
    @assignment.destroy
    flash[:notifications] = ["Assignment \"#{@assignment.name}\" successfully destroyed"]
    redirect_to "/"
  end

  def get_csv
    @assignment = Assignment.find(params[:id])
    render :text => @assignment.marks_csv
  end

  def get_zipfile
    @assignment.update_zip
    send_file(@assignment.zip_path)
  end

  def peer_review
    @assignment.start_peer_review
    redirect_to @assignment
  end
end

app/views/assignments/_form.html.erb
<div class="row">
  <div class="alert alert-info col-sm-5 col-sm-offset-3">I've changed up how custom behaviour happens. It's now similar to how the peer review cycles work. It's in the options menu on the assignment show page.</div>
</div>

<input type="hidden" name="assignment[group_type_id]" value="<%= assignment.group_type_id %>">

<div class="form-group">
  <%= label_tag(:name, "Name", :class => "col-sm-2 col-sm-offset-2") %>
  <div class="col-sm-5">
    <%= f.text_field(:name, :class => "form-control") %>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-2 col-sm-offset-2">
    Group type
  </label>
  <div class="col-sm-5">
    <%= assignment.group_type.name %>
  </div>
</div>
<div class="form-group">
  <%= label_tag(:due_date, "Due date", :class => "col-sm-2 col-sm-offset-2") %>
  <div class="col-sm-5">
    <%= f.datetime_select(:due_date, :class => "form-control") %>
    <br />For timezone inference, when you loaded this page the time was <%= Time.zone.now %>
  </div>
</div>

<div class="row">
  <div class="col-sm-7 col-sm-offset-2">
    <%= f.check_box(:is_due_date_compulsary) %>
    <label> Stop accepting submissions after due date</label>
    <span class="help-block">If this isn't selected, users continue to be able to submit after the due date.</span>
  </div>
</div>

<div class="row">
  <label for="assignment_info" class="col-sm-6 col-sm-offset-2">Assignment description</label>
</div>
<div class="row">
  <div class="col-sm-7 col-sm-offset-2">
    <textarea class="form-control" id="assignment_info" rows="10" name="assignment[info]"><%= assignment.info %></textarea>
  </div>
</div>

<div class="row">
  <label for="assignment_submission_instructions" class="col-sm-6 col-sm-offset-2">Submission instructions</label>
</div>
<div class="row">
  <div class="col-sm-7 col-sm-offset-2">
    <textarea class="form-control" id="assignment_submission_instructions" rows="10" name="assignment[submission_instructions]"><%=assignment.submission_instructions%></textarea>
    <span class="help-block">This is displayed when students are trying to submit their assignments.</span>
  </div>
</div>

<div class="form-group">
  <%= label_tag(:submission_format, "Submission format", :class => "col-sm-2 col-sm-offset-2") %>
  <div class="col-sm-5">
    <%= f.select(:submission_format,
      options_for_select([
        ['Plain text', 'plaintext'], ['Zip file', 'zipfile']], assignment.submission_format)) %><br>
  </div>
</div>

<div class="form-group">
  <%= label_tag(:filepath_regex, "Filepath regex", :class => "col-sm-2 col-sm-offset-2") %>
  <div class="col-sm-5">
    <%= f.text_field(:filepath_regex, :class => "form-control",
        :html => { :placeholder => ".hs .txt", :rows => 3 }) %>
  <span class="help-block">This determines what filetypes are displayed in the web interface. For instance, if you had <code>.*(\.hs|\.txt)</code>, it would only display files ending with .hs and .txt.</span>
  </div>
</div>

<div class="row">
  <div class="col-sm-7 col-sm-offset-2">
    <%= f.check_box(:is_visible) %>
    <label> Visible
    </label>
    <span class="help-block">If this isn't selected, students aren't able to see this assignment.</span>
  </div>
</div>

<div class="row">
  <div class="col-sm-7 col-sm-offset-2">
    <%= f.check_box(:visible_comments) %>
    <label>Comments visible
    </label>
    <span class="help-block">If this isn't selected, students aren't able to see comments on an assignment.</span>
  </div>
</div>

app/views/assignments/_show_info.html.erb
<p><em>Assignment for
  <%= link_to(assignment.group_type.name, assignment.group_type) %></em>
</p>
<% unless @assignment.is_visible %>
  <p><strong>This assignment has not been released yet. Students cannot see it.</strong></p>
<% end %>
<!--
<p>This is an assignment for the following courses:</p>

<ul>
  <% assignment.courses.each do |course| %>
    <li>
      <%= link_to course.name, course_url(course) %>
    </li>
  <% end %>
</ul>
 -->
<% if assignment.due_date %>
  <p>Due at <%= assignment.due_date %> </p>
<% end %>

<!-- <h3>Description</h3> -->
<p id="annotate-me">
  <%= sanitize assignment.info, tags: %w(li ul ol code strong em b a) %>
</p>

<% if assignment.marking_categories.length > 0 || assignment.conveners.include?(current_user) %>
  <h3>Marking scheme
  <% if assignment.conveners.include?(current_user) %>
  <span class="small"><%= link_to "edit", assignment_marking_categories_url(assignment) %>
  </span>
  <% end %>
  </h3>
  <% if assignment.marking_categories.empty? %>
    <p>This assignment is not marked.</p>
  <% else %>
    <% assignment.marking_categories.each do |category| %>
      <h4><%= category.name %>
        <small>(<%= category.maximum_mark %> marks)</small>
      </h4>
      <p><%= category.description %></p>
    <% end %>
  <% end %>
<% end %>

app/views/assignments/edit.html.erb
<% content_for :title, "Edit " + @assignment.name %>
<div class="row">
  <div class="col-sm-9 col-sm-offset-2">
    <h2>Edit <%= link_to @assignment.name, @assignment %></h2>
  </div>
</div>

<%= form_for(@assignment, html: {:class => "form-horizontal", :role => "form"},
                            url: {action: "update"}) do |f| %>

  <%= render :partial => "form", :locals => {:f => f, :assignment => @assignment} %>

  <div class="row">
    <div class="col-sm-7 col-sm-offset-2">
      <div class="btn-group">
        <button type="button" class="btn btn-danger" data-toggle="modal"
                data-target="#myModal">
          Delete
        </button>

        <input class="btn btn-primary" type="submit" value="Update">
      </div>
    </div>
  </div>

<% end %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Deleting <%= @assignment.name %></h4>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this assignment?

        If you delete the assignment, it will be gone forever, but all submissions to the assignment will remain in the directory <%= @assignment.path %> on the server, where your IT guy might be able to recover them for you. Comments and marks on the assignment are not recoverable.
      </div>
      <div class="modal-footer">
        <%= link_to "Delete assignment", @assignment, :method => :delete,
          :class => "btn btn-danger", :style => "float: left" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/assignments/new.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-offset-2">
    <h2>New assignment</h2>
  </div>
</div>
<%= form_for @assignment, html: {:class => "form-horizontal", :role => "form"},url: {action: "create"} do |f| %>

  <%= render partial: "form", :locals => {:f => f, :assignment => @assignment}%>

  <div class="row">
    <div class="col-sm-2 col-sm-offset-2 col-xs-4">
      <%= f.submit("Create assignment", :class => "btn btn-default") %>
    </div>
  </div>
<% end %>

app/views/assignments/show.html.erb
<h3><%= @assignment.name %></h3>

This is an assignment for the following courses:

<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to course.name, course_url(course) %>
    </li>
  <% end %>
</ul>

<h3>Your submissions</h3>
<ul>
  <% @user_submissions.each do |submission| %>
    <li> <%= link_to(submission.created_at,
              assignment_assignment_submission_url(
                        @assignment, submission)) %> </li>
  <% end %>
</ul>

<%= link_to "Submit assignment", new_assignment_assignment_submission_url(
                                                                @assignment)%>

app/views/assignments/show_to_staff.html.erb
<% content_for :title, @assignment.name %>
<div class="row">
  <div class="col-sm-5 col-sm-offset-2">
    <h2><%= @assignment.name %></h2>
  </div>


  <% if @relation == :convener || current_user.is_admin %>
    <div class="col-sm-3">
      <div class="btn-group pull-right pull-down extra_space_button">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          Options <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Edit", edit_assignment_url(@assignment) %></li>
          <li><%= link_to "View all marks as csv",
                assignment_marks_url(@assignment) %></li>
          <li><%= link_to "Peer review cycles",
                assignment_cycles_url(@assignment) %></li>
          <li><%= link_to "Custom behaviors",
                assignment_custom_behaviors_url(@assignment) %></li>
          <li><%= link_to "Extensions",
                assignment_extensions_url(@assignment) %></li>
          <li><%= link_to "Marking scheme",
                assignment_marking_categories_url(@assignment) %></li>
          <li class="divider"></li>
          <li><%= link_to "Download all submissions as zip",
                assignment_zipfile_url(@assignment) %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

    <%= render :partial => "show_info",
                            :locals => { :assignment => @assignment,
                                        :courses => @courses} %>

    <h3>Submissions</h3>
        <% if @relation == :staff || @relation == :convener %>
<!--           As a tutor, you can't currently download all of your students'
        submissions as a zip. Sorry about that. You can, however, view and download them individually. -->
        <p>
          <%= link_to "Download all submissions as zip",
            "/assignments/#{@assignment.id}/submissions.zip", 
            {:class => "btn btn-primary btn-sm"} %>
        <% end %>

          <%= link_to("Submit test submission",
            new_assignment_assignment_submission_url(@assignment), 
            {:class => "btn btn-primary btn-sm"}) %>
        </p>

    <div class="panel panel-default">
      <div class="panel-body">
        <h4>Progress</h4>

        <% if @number_students > 0 %>
          <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-success" style="width: <%=
                    @number_finalized * 100.0 / @number_students %>%">
            </div>
            <div class="progress-bar progress-bar-warning" style="width: <%=
                    (@number_submitted- @number_finalized) * 100.0 / @number_students %>%">
            </div>
            <div class="progress-bar progress-bar-danger" style="width: <%=
                    (@number_students- @number_submitted) * 100.0 / @number_students %>%">
            </div>
          </div>

          <table class="table table-bordered table-striped">
            <tr>
              <td>Students who have submitted</td>
              <td><%= @number_submitted %></td>
            </tr>
            <tr>
              <td>Students who have finalized</td>
              <td><%= @number_finalized %></td>
            </tr>
            <tr>
              <td>Total number of students</td>
              <td><%= @number_students %></td>
            </tr>
          </table>

          <h4>By group</h4>
          <ul>
          <% user_groups = current_user.is_admin_or_convener? ? @assignment.groups : current_user.staffed_groups & @assignment.groups %>
          <table class="table table-condensed table-bordered table-striped">
            <% user_groups.each do |group| %>
              <tr>
                <td>
                  <lead><%= link_to group.name, assignment_group_show_url(@assignment, group) %></lead>
                </td>
                <td style="width:70%;">
                  <% progress_hash = group.progress_bar_hash(@assignment) %>
                  <a href="<%= assignment_group_show_url(@assignment, group) %>">
                    <div class="progress progress-striped active">
                        <div class="progress-bar" style="width: <%= progress_hash[:percent_marked] %>%"></div>
                      <div class="progress-bar progress-bar-success" style="width: <%= progress_hash[:percent_finalized] %>%">
                      </div>
                      <div class="progress-bar progress-bar-warning" style="width: <%= progress_hash[:percent_submitted] %>%">
                      </div>
                      <div class="progress-bar progress-bar-danger" style="width: <%= progress_hash[:percent_not_submitted] - progress_hash[:percent_finalized]%>%">
                      </div>
                    </div>
                  </a>
                </td>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>

    <h4>Raw list of all submissions (all <%= @submissions.count %> of them)</h4>
<!-- <p>TODO: currently when you download all submissions as a zip, none of them are labelled, and some of them are old submissions. How should I label them? Which ones should be downloaded?</p> -->
      <!-- Submission table -->
      <table id="raw-submissions" class="table table-bordered table-striped">
        <tr>
          <th><h5>Student</h5></th>
          <th><h5>ID</h5></th>
          <% if @assignment.peer_review_cycles.any? %>
            <th><h5>Visible to</h5></th>
          <% end %>
          <th><h5>Status</h5></th>
        </tr>
        <% @submissions.each do |submission| %>
            <tr>
              <!-- User info -->
              <td><%= link_to "#{submission.user.name}",
                  assignment_assignment_submission_url(@assignment, submission) %></td>
              <td><%= link_to "u#{submission.user.uni_id}",
                  user_url(submission.user) %></td>
              <!-- Peer reviewer -->
              <% if @assignment.peer_review_cycles.any? %>
                <td>
                  <% unless submission.submission_permissions.empty? %>
                    <%= submission.permitted_users.pluck(:name).join(", ") %>
                  <% end %>
                </td>
              <% end %>
                  
              <td>
                <!-- Submission status -->
                <% if submission.is_finalized %>
                  <span class="label label-success">Finalized</span>
                <% else %>
                  <span class="label label-warning">Not finalized</span>
                <% end %>
                <% if @assignment.peer_review_cycles.any? %>
                  <% if (submission.comments.where_not_automated.count == 0) && 
                      (@assignment.peer_review_cycles.any?) %>
                    <span class="label label-default">Not Reviewed</span>
                  <% else %>
                    <span class="label label-success">Reviewed</span>
                  <% end %>
                <% end %>
              </td>
            </tr>
        <% end %>
      </table>
      
         <!-- TODO: add this feature back in -->
         <!--  <%# unless submission.mark %>
            <span class="label label-default">(unmarked)</span>
-->
</div>

app/views/assignments/show_to_student.html.erb
<% content_for :title, @assignment.name %>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h2><%= @assignment.name %></h2>

    <%= render :partial => "show_info",
                            :locals => {:assignment => @assignment,
                                            :courses => @courses} %>

    <h3>Your submissions</h3>
    <% extension = current_user.extensions.where(:assignment_id => @assignment.id).first %>
    <% if extension %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p>You have an extension on this assignment until <%= extension.due_date %>.</p>
      </div>
    <% end %>

    <% if @user_submissions.empty? %>
      <p>You haven't submitted anything.</p>
    <% else %>
      <ul>
        <% @user_submissions.each do |submission| %>
          <li> <%= link_to(submission.created_at,
                    assignment_assignment_submission_url(
                              @assignment, submission)) %> </li>
        <% end %>
      </ul>
    <% end %>

    <% if @assignment.disable_submitting_until_comment(current_user) %>
      <p>You can't submit again until you've commented on your peer review
        submissions.</p>
    <% elsif @assignment.already_due(current_user) %>
      <p>Submissions have closed.</p>
    <% else %>
      <%= link_to("Submit assignment",
                new_assignment_assignment_submission_url(@assignment), :class => "btn btn-primary btn-sm") %>
    <% end %>


    <% unless @permitted_submissions.empty? %>
      <h3>Submissions for peer review</h3>
      <table id="peer-review" class="table table-bordered table-striped">
      <% @permitted_submissions.each do |submission| %>
        <td> <%= link_to("Submission #{submission.id}",
                  assignment_assignment_submission_url(
                            @assignment, submission)) %>
        </td>
        <td>
            <% if submission.commented_on_by_user?(current_user) %>
              <span class="label label-success">Reviewed</span>
            <% else %>
              <span class="label label-warning">Not Reviewed</span>
            <% end %>
        </td>
      <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/assignments/show_to_students.html.erb
<h3><%= @assignment.name %></h3>

This is an assignment for the following courses:

<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to course.name, course_url(course) %>
    </li>
  <% end %>
</ul>

<h3>Your submissions</h3>
<ul>
  <% @user_submissions.each do |submission| %>
    <li> <%= link_to(submission.created_at,
              assignment_assignment_submission_url(
                        @assignment, submission)) %> </li>
  <% end %>
</ul>

<%= link_to "Submit assignment", new_assignment_assignment_submission_url(
                                                                @assignment)%>