config/routes.rb
SubmissionApp::Application.routes.draw do
  # get "groups/show"

  # get "group/show"

  resource :sessions, :only => [:new, :create, :destroy]

  resources :courses, :only => [:new, :create, :index, :show, :destroy] do
    resources :users, :only => [:new, :create]
    resources :student_enrollments, :only => [:create, :destroy]
  end

  resources :users, :only => [:show, :index, :destroy]

  resources :group_types do
    resources :assignments, :only => [:new]
    resources :groups, :only => [:create]
    post 'csv', :to => 'group_types#edit_by_csv', :as => 'edit_by_csv'
  end

  resources :groups, :only => [:show]

  resources :assignments, :only => [:show, :create, :destroy, :edit, :update] do
    resources :assignment_submissions, :except => [:update, :edit] do
      resources :comments, :only => [:create, :destroy]
      post 'finalize', :to => 'assignment_submissions#finalize',
                       :as => "finalize"
      get 'printable', :to => 'assignment_submissions#printable',
                        :as => "printable"
      get 'pdf', :to => 'assignment_submissions#pdf',
                 :as => 'pdf'
    end

    get 'groups/:id', :to => 'groups#assignment_show', :as => 'group_show'
    get 'groups/:id/zip', :to => 'groups#assignment_zip', :as => 'group_zip'


    get 'cycles', :to => 'peer_review_cycles#index', :as => "cycles"
    post 'cycles', :to => 'peer_review_cycles#create'
    put 'cycles/:id/edit', :to => 'peer_review_cycles#update'
    delete 'cycles/:id', :to => 'peer_review_cycles#delete', :as => "cycles_delete"
    get 'cycles/:id/edit', :to => 'peer_review_cycles#edit', :as => "cycles_edit"
    post 'cycles/:id/activate', :to => 'peer_review_cycles#activate',
                                :as => "cycle_activate"
    post 'cycles/:id/deactivate', :to => 'peer_review_cycles#deactivate',
                                :as => "cycle_deactivate"

    resources :marking_categories, :only => [:create, :destroy, :update, :index]
    resources :custom_behaviors, :only => [:create, :destroy, :update, :index]

    resources :extensions, :only => [:index, :create]
  end

  resources :extensions, :only => [:destroy]

  resources :notifications, :only => [:destroy, :index]

  get 'assignments/:id/marks.csv', :to => 'assignments#get_csv',
                                   :as => 'assignment_marks'

  get 'assignments/:id/submissions.zip', :to => 'assignments#get_zipfile',
                                         :as => 'assignment_zipfile'

  post 'assignments/:id/peer_review', :to => 'assignments#peer_review',
                                      :as => 'assignment_peer_review'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/file.zip',
                                    :to => 'assignment_submissions#get_zip',
                                    :as => 'assignment_submission_zip'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/Main.hs',
                                    :to => 'assignment_submissions#download_raw',
                                    :as => 'assignment_submission_raw'

  get 'comment_files/:id', :to => 'comments#get_file',
                           :as => 'comment_file'

  root :to => 'courses#index'

  get 'admin/log', :to => 'admin#log'
  get 'admin/summary_log', :to => 'admin#summary_log'
  get 'admin/database', :to => 'admin#database'
  get 'admin/spoof-login/:id', :to => 'admin#spoof_login'
  get 'admin/charts', :to => 'admin#charts'

  get 'files/:id', :to => 'submission_files#serve', :as => 'file_serve'
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :group_type_id, :group_type

  belongs_to :group_type
  has_many :courses, :through => :group_type, :source => :courses

  has_many :group_student_memberships
  has_many :students, :through => :group_student_memberships, :source => :user

  has_many :group_staff_memberships
  has_many :staff, :through => :group_staff_memberships, :source => :user

  has_many :assignments, :through => :group_type, :source => :assignment

  def self.by_group_type(type)
    where(group_type_id: type.id)
  end

  # do
  #   def find_by_group_type(group_type)
  #     where(:group_type_id => group_type.id)
  #   end
  # end


  def self.touch(name, group_type)
    g = Group.find_by_name_and_group_type_id(name, group_type.id)
    return g if g
    Group.create!(:group_type => group_type, :name => name)
  end

  def submissions(assignment)
    self.
    # TODO: rewrite this as SQL
    assignment.submissions.select do |submission|
      self.students.include?(submission.user)
    end
  end

  def jettison_staff
    GroupStaffMembership.delete_all(:group_id => self.id)
  end

  def progress_bar_hash(assignment)
    {}.tap do |out|
      number_students = self.students.count
      return Hash.new(0) if number_students == 0
      number_marked = assignment.submissions
                                .where("user_id IN (#{self.student_ids.join(",")})")
                                .select { |s| s.comments.where(:user_id != s.user_id).count > 0  }
                                .length

      number_submitted = assignment.submissions
                                     .where("user_id IN (#{self.student_ids.join(",")})")
                                     .group(:user_id).count.count

      number_finalized = assignment.submissions
                                      .where("user_id IN (#{self.student_ids.join(",")})")
                                      .where(:is_finalized => true)
                                      .group(:user_id).count.count

      if number_marked > number_finalized
        out[:percent_finalized] = 0
        out[:percent_submitted] = [0, (number_submitted - number_marked
                              - number_finalized)].max * 100 / number_students
      else
        out[:percent_finalized] = (number_finalized - number_marked) * 100 / number_students
        out[:percent_submitted] = ((number_submitted - number_finalized) * 100 / number_students)
      end

      out[:percent_marked] = ([number_marked, number_submitted].min * 100 / number_students)
      out[:percent_not_submitted] = (100 - [out[:percent_submitted] + out[:percent_finalized],
                                               out[:percent_marked]].max)
    end
  end

  def sanitize(filename)
    filename.strip!
    filename.gsub!(/^.*(\\|\/)/, '') # remove slashes etc
    filename.gsub!(/[^0-9A-Za-z.\-]/, '_') # remove non-ascii
    return filename
  end

  def make_group_zip(assignment)
    folder_name = "#{sanitize(self.name)}_#{sanitize(assignment.name)}"
    p "Creating folder for group submissions: "+folder_name
    system("mkdir /tmp/#{folder_name}")
    self.students.each do |student|

      sub = student.most_recent_submission(assignment)

      next if sub.nil?
      if !File.exists?(sub.zip_path(assignment))
        next
      end

      sub_name = "u#{sub.user.uni_id.to_s}_#{sub.user.name.gsub(" ","_")}_#{sub.id}"
      if sub
        system("mkdir /tmp/#{folder_name}/#{sub_name}")
        system("unzip -o #{sub.zip_path(assignment)} -d /tmp/#{folder_name}/#{sub_name}")
        # x = "mv #{folder_name}#{sub.file_path_without_assignment_path}.zip #{folder_name}/#{sub_name}"
        # p x
        # system(x)
      end
    end
    system("cd /tmp/#{folder_name}/ && zip -r ../#{folder_name}.zip .")
    system("rm -rf /tmp/#{folder_name}")
    "/tmp/" + folder_name + ".zip"
  end
end

app/models/group_type.rb
class GroupType < ActiveRecord::Base
  attr_accessible :name, :courses, :groups

  has_many :group_course_memberships, :dependent => :destroy
  has_many :courses, :through => :group_course_memberships, :source => :course

  has_many :groups, :dependent => :destroy
  has_many :assignments, :dependent => :destroy

  has_many :students, :through => :groups, :source => :students
  has_many :staff, :through => :groups, :source => :staff
  has_many :conveners, :through => :courses, :source => :convener

  validates :name, uniqueness: true

  def create_groups(group_hash)
    [].tap do |groups|
      group_hash.each do |name, staff|
        group = Group.create(:name => name, :group_type_id => self.id)
        staff.each do |user|
          user.join_group_as_staff!(group)
        end
        groups << group
      end
    end
  end

  def add_course!(course)
    GroupCourseMembership.create!(:group_type_id => self.id, :course_id => course.id)
  end

  def update_student_membership(user, group_name)
    current_group = user.student_groups
                        .where(:group_type_id => self.id)
                        .first

    if current_group.nil?
      unless group_name == "" || group_name.nil?
        user.join_group!(Group.touch(group_name, self))
        return {:joins => 1, :changes => 0}
      end
    else
      unless group_name == current_group.name
        user.drop_group!(current_group)
        user.join_group!(Group.touch(group_name, self))
        return {:changes => 1, :joins => 0}
      end
    end
    Hash.new(0)
  end

  def update_staff_membership(user, group_name)
    current_group = user.staffed_groups
                        .where(:group_type_id => self.id)
                        .first

    if current_group.nil?
      unless group_name == ""
        user.join_group_as_staff!(Group.touch(group_name, self))
      end
    else
      unless group_name == current_group.name
        user.drop_group_as_staff!(current_group)
        user.join_group_as_staff!(Group.touch(group_name, self))
        self.courses.each do |course|
          user.enroll_staff_in_course(course)
        end
      end
    end
  end

  def render_csv
    out = ["group name,staff_uid..."]
    self.groups.each do |group|
      row = []
      row << group.name
      row += group.staff.map(&:uni_id)
      out << row.join(",")
    end
    return out.join("\n")
  end

  def edit_by_csv(csv_string)
    ActiveRecord::Base.transaction do
      lines = csv_string.split("\n")

      unless "group name,staff_uid..." == lines[0].chomp
        raise "invalid csv"
      end

      groups_seen = []
      puts "\n"*30

      lines.drop(1).each do |line|
        row = line.chomp.split(",")
        g = Group.touch(row[0], self)
        g.jettison_staff
        row.drop(1).uniq.each do |staff_uni_id|
          u = User.find_by_uni_id(staff_uni_id)
          u.join_group_as_staff!(g)
        end
        groups_seen << g
      end
      (self.groups - groups_seen).map(&:delete)
    end
  end

  def students_of_courses
    where_clause = <<-SQL
    student_enrollments.course_id IN
        (SELECT courses.id
          FROM courses
          JOIN group_course_memberships
          ON courses.id = group_course_memberships.course_id
          WHERE group_course_memberships.group_type_id = #{self.id})
    SQL

    User.joins(:student_enrollments).where(where_clause)
  end

  def students_without_a_group_count
    self.students_of_courses.count - self.students.count
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :require_logged_in
  before_filter :require_permission, :only => [:assignment_show]

  def require_permission
    return if current_user.is_admin

    @assignment = Assignment.find(params[:assignment_id])
    unless @assignment.conveners_and_staff.include?(current_user)
      flash[:errors] = ["You don't have permission to do that with assignments."]
      redirect_to @assignment
    end
  end

  def show
    @group = Group.find(params[:id])
    @group_type = @group.group_type
    @users = @group.students.sort_by!{|x| x.name.split(" ").last}
    @staff = @group.staff
    render :show
  end

  def assignment_show
    @assignment = Assignment.find(params[:assignment_id])
    @group = Group.find(params[:id])
    @students = @group.students.sort_by!{|x| x.name.split(" ").last}
    render :assignment_show
  end

  def assignment_zip
    @assignment = Assignment.find(params[:assignment_id])
    @group = Group.find(params[:id])
    @students = @group.students.sort_by!{|x| x.name.split(" ").last}
    send_file(@group.make_group_zip(@assignment))
  end
end

app/views/groups/assignment_show.html.erb
<% content_for :title, "#{@group.name}: #{@assignment.name}" %>

<div class="container-fluid">
  <!--<div class="container">-->
  <div class="col-md-10 col-md-offset-1">
    <h2>Submissions for <%= @assignment.name %> from <%= @group.name %></h2>

    <p><%= link_to("<span class=\"glyphicon glyphicon-download\"></span> Download all submissions as a zip".html_safe,
               assignment_group_zip_url(@assignment, @group),
                :class => "btn btn-primary") %></p>

    <table class="table" id="accordion">
      <tr>
        <th>UID</th>
        <th>Name</th>
        <th>Status</th>
        <th>Submissions</th>
        <th>Specs passing</th>
        <% if @assignment.peer_review_cycles.count > 0 %>
          <th>Peer review status</th>
        <% end %>
        <th>Staff comment</th>
        <% if @assignment.marking_categories.length > 0 %>
          <th>Marks</th>
        <% end %>
        <th>Add comment</th>
      </tr>

      <% @students.each do |student| %>
        <tr>
          <td><%= link_to("u" + student.uni_id.to_s, student) %></td>
          <td><%= link_to(student.name, student) %></td>

          <!-- Submission status -->

          <% if student.has_submitted_for_assignment(@assignment) %>
            <% if student.has_finalized_for_assignment(@assignment) %>
              <td class="success">Finalized</td>
            <% else %>
              <td>Submitted</td>
            <% end %>
          <% else %>
            <td class="warning"><strong>No submission</strong></td>
          <% end %>

          <td>
            <% student.submissions_for_assignment(@assignment).each do |s| %>
              <% if s.is_finalized %> <strong> <% end %>
              <%= link_to s.id, assignment_assignment_submission_url(s.assignment, s) %>
              <% if s.is_finalized %> </strong> <% end %>
            <% end %>
          </td>

          <!-- Specs passing -->

          <td>
            <%= (student.most_recent_submission(@assignment)
                       .try(:specs_passing)) || "N/A" %>
          </td>


          <!-- Peer review status -->
          <% if @assignment.peer_review_cycles.count > 0 %>
            <% if (student.uncommented_submissions_for_assignment(@assignment)
                        .count) > 0 %>
                <td class="warning"><strong>No comment made</strong></td>
            <% else %>
              <% if (student.permitted_submissions_for_assignment(@assignment)
                        .count) > 0 %>
                <td class="success">Commented</td>
              <% else %>
                <td>Not reviewed</td>
              <% end %>
            <% end %>
          <% end %>

          <!-- Commenting -->
          <% mra = student.most_recent_submission(@assignment) %>
          <% if mra %>
            <% if mra.comments.where(
              "comments.user_id IS NOT NULL AND comments.user_id != #{student.id}").count == 0 %>
              <td class="warning"><strong>No comment made</strong></td>
            <% else %>
              <td class="success">Commented</td>
            <% end %>
          <% else %>
            <td>No submission</td>
          <% end %>

          <% if @assignment.marking_categories.length > 0 %>
            <td><%= (s = student.most_recent_submission(@assignment)) &&
                                  s.marks.pluck(:value).join(", ") %></td>
          <% end %>

          <!-- File upload -->
          <% if mra %>

            <td width="30%">
            <a data-toggle="collapse" data-parent="#accordion" href="#comment-<%= mra.id %>">
              Add comment
            </a>
              <form method="POST"
            action="<%= assignment_assignment_submission_comments_url(
                      @assignment, mra)%>"
            enctype="multipart/form-data"
            role="form"
            class="form collapse"
            id="comment-<%= mra.id %>"
            >
                <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

                <input type="text" name="comment[body]" value="">
                <%= file_field 'upload', 'datafile' %>

                <input class="btn btn-primary btn-xs" type="submit" value="Post comment">
              </form>
            </td>
          <% else %>
            <td>N/A</td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h2><%= @group.name %></h2>
    <p><%= @group.name %> is an instance of <%= link_to @group_type.name, @group_type %>.</p>

    <h3>Staff</h3>
    <table id="students" class="table table-bordered table-striped">
      <% @staff.each do |staff| %>
          <tr>
            <!-- User info -->
            <td><%= link_to staff.name, user_url(staff) %></td>
          </tr>
      <% end %>
    </table>

    <h3>Students</h3>
    <table id="students" class="table table-bordered table-striped">
        <tr>
          <th><h5>Student</h5></th>
          <th><h5>ID</h5></th>
        </tr>
        <% @users.each do |student| %>
            <tr>
              <!-- User info -->
              <td><%= link_to student.name, user_url(student) %></td>
              <td><%= link_to "u" + student.uni_id.to_s, user_url(student) %></td>
            </tr>
        <% end %>
      </table>
  </div>
</div>