config/routes.rb
SubmissionApp::Application.routes.draw do
  # get "groups/show"

  # get "group/show"

  resource :sessions, :only => [:new, :create, :destroy]

  resources :courses, :only => [:new, :create, :index, :show, :destroy] do
    resources :users, :only => [:new, :create]
    resources :student_enrollments, :only => [:create, :destroy]
  end

  resources :users, :only => [:show, :index, :destroy]

  resources :group_types do
    resources :assignments, :only => [:new]
    resources :groups, :only => [:create]
    post 'csv', :to => 'group_types#edit_by_csv', :as => 'edit_by_csv'
  end

  resources :groups, :only => [:show]

  resources :assignments, :only => [:show, :create, :destroy, :edit, :update] do
    resources :assignment_submissions, :except => [:update, :edit] do
      resources :comments, :only => [:create, :destroy]
      post 'finalize', :to => 'assignment_submissions#finalize',
                       :as => "finalize"
      get 'printable', :to => 'assignment_submissions#printable',
                        :as => "printable"
      get 'pdf', :to => 'assignment_submissions#pdf',
                 :as => 'pdf'
    end

    get 'groups/:id', :to => 'groups#assignment_show', :as => 'group_show'
    get 'groups/:id/zip', :to => 'groups#assignment_zip', :as => 'group_zip'


    get 'cycles', :to => 'peer_review_cycles#index', :as => "cycles"
    post 'cycles', :to => 'peer_review_cycles#create'
    put 'cycles/:id/edit', :to => 'peer_review_cycles#update'
    delete 'cycles/:id', :to => 'peer_review_cycles#delete', :as => "cycles_delete"
    get 'cycles/:id/edit', :to => 'peer_review_cycles#edit', :as => "cycles_edit"
    post 'cycles/:id/activate', :to => 'peer_review_cycles#activate',
                                :as => "cycle_activate"
    post 'cycles/:id/deactivate', :to => 'peer_review_cycles#deactivate',
                                :as => "cycle_deactivate"

    resources :marking_categories, :only => [:create, :destroy, :update, :index]
    resources :custom_behaviors, :only => [:create, :destroy, :update, :index]

    resources :extensions, :only => [:index, :create]
  end

  resources :extensions, :only => [:destroy]

  resources :notifications, :only => [:destroy, :index]

  get 'assignments/:id/marks.csv', :to => 'assignments#get_csv',
                                   :as => 'assignment_marks'

  get 'assignments/:id/submissions.zip', :to => 'assignments#get_zipfile',
                                         :as => 'assignment_zipfile'

  post 'assignments/:id/peer_review', :to => 'assignments#peer_review',
                                      :as => 'assignment_peer_review'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/file.zip',
                                    :to => 'assignment_submissions#get_zip',
                                    :as => 'assignment_submission_zip'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/Main.hs',
                                    :to => 'assignment_submissions#download_raw',
                                    :as => 'assignment_submission_raw'

  get 'comment_files/:id', :to => 'comments#get_file',
                           :as => 'comment_file'

  root :to => 'courses#index'

  get 'admin/log', :to => 'admin#log'
  get 'admin/summary_log', :to => 'admin#summary_log'
  get 'admin/database', :to => 'admin#database'
  get 'admin/spoof-login/:id', :to => 'admin#spoof_login'
  get 'admin/charts', :to => 'admin#charts'

  get 'files/:id', :to => 'submission_files#serve', :as => 'file_serve'
end

app/models/assignment_submission.rb
require "zip"

class AssignmentSubmission < ActiveRecord::Base
  include CheckingRules
  include SubmissionFileStuffHelper
  include PeerReviewHelper

  attr_accessible :assignment_id, :body, :user_id

  belongs_to :assignment
  belongs_to :user

  has_many :comments, :dependent => :destroy
  has_many :marks, :through => :comments, :source => :marks
  has_many :peer_marks, :through => :comments, :source => :peer_marks

  has_many :submission_permissions, :dependent => :destroy

  has_many :permitted_users, :through => :submission_permissions,
                             :source => :user

  has_many :submission_files

  has_one :group_type, :through => :assignment, :source => :group_type
  has_many :courses, :through => :group_type, :source => :courses
  has_many :conveners, :through => :courses, :source => :convener

  validates :assignment_id, :user_id, :presence => true

  def self.group_by_day(field)
    AssignmentSubmission.group("CAST(assignment_submissions.#{field} AS DATE)")
  end

  def self.uncommented(user)
    where(<<-SQL, user.id)
      (SELECT COUNT(*)
      FROM comments
      WHERE comments.assignment_submission_id = assignment_submissions.id
      AND comments.user_id = ?) = 0
    SQL
  end

  def self.where_user_is(user)
    where(:user_id => user.id)
  end

  def self.where_assignment_is(assignment)
    where(:assignment_id => assignment.id)
  end

  def self.finalized
    where(:is_finalized => true)
  end

  def group
    #TODO: this is probably inefficient. Rewrite it properly.
    self.user.student_groups.each do |group|
      if group.group_type == self.assignment.group_type
        return group
      end
    end
    return nil
  end

  # TODO: remove the n+1 query
  def relationship_to_user(user)
    if user == self.user
      return :creator
    elsif (assignment.courses.map(&:staff).flatten +
                        assignment.courses.map(&:convener)).include?(user) ||
                            user.is_admin
      return :staff
    elsif self.which_peer_review_cycle(user)
      return :peer
    end
  end

  # This is all the people who are permitted to see the assignment.
  # TODO: make it so that the assignment has a setting to let all
  # staff for the course see all the submissions.
  # Also, faster, obviously
  def staff
    group.staff + group.group_type.courses.map(&:convener)
  end

  def permits?(user)
    !! self.relationship_to_user(user)
  end


  def finalize!
    logger.info "finalizing assignment submission #{id}"
    return if self.is_finalized
    self.is_finalized = true
    self.assignment.peer_review_cycles.each do |cycle|
      cycle.receive_submission(self)
    end
    self.save!
  end

  def add_anonymous_comment(body)
    Comment.create!(:body => body, :assignment_submission_id => self.id)
  end

  def top_level_comments
    self.comments.where(:parent_id => nil)
  end


  # If a user has access to a submission through two seperate cycles, the
  # latter one controls the conditions of viewing.
  # This shouldn't happen though.
  def which_peer_review_cycle(user)
    permission = self.submission_permissions.where(:user_id => user.id)
                               .order('created_at DESC')
                               .first

    if permission.try(:peer_review_cycle).try(:activated)
      permission.peer_review_cycle
    end
  end

  def commented_on_by_user?(user)
    ! self.comments.select { |c| c.user == user }
                   .empty?
  end

  def receive_submission
    self.save_locally
    self.assignment.custom_behaviors.each do |behavior|
      behavior.receive_submission(self)
    end
  end
end

app/controllers/assignment_submissions_controller.rb
class AssignmentSubmissionsController < ApplicationController
  before_filter :require_logged_in

  def show
    @submission = AssignmentSubmission.find(params[:id], include: :submission_files)
    @assignment = @submission.assignment
    @comments = @submission.comments
    @relationship = @submission.relationship_to_user(current_user)

    current_user.notifications.where(:notable_type => "AssignmentSubmission",
                                     :notable_id => @submission.id).delete_all

    current_user.notifications.where(:notable_type => "Comment")
                              .includes(:notable)
                              .select { |s| s.notable.assignment_submission_id == @submission.id }
                              .map(&:delete)

    if (@relationship == :staff) || 
      (@submission.permitted_users.pluck(:uni_id).include? current_user.uni_id) ||
      (@submission.user == current_user)
      render :show
    else
      flash[:errors] = ["You don't have permission to access that page"]
      redirect_to "/"
    end
  end

  def new
    @assignment = Assignment.find(params[:assignment_id])

    relationship = current_user.relationship_to_assignment(@assignment)
    #NOTE: this allows the user to be a staff member.
    unless relationship || current_user.is_admin
      flash[:errors] = ["You're not allowed to submit that assignment..."]
      redirect_to courses_url
      return
    end

    if relationship == :student && !@assignment.is_visible
      flash[:errors] = ["That assignment isn't visible yet."]
      redirect_to "/"
      return
    end

    unless @assignment.already_due(current_user)
      if @assignment.submission_format == "plaintext"
        @submission = @assignment.submissions
                   .where(:user_id => current_user.id)
                   .order(:created_at)
                   .last
      end
      render :new
    else
      flash[:errors] = ["Assignment is already due."]
      redirect_to assignment_url(@assignment)
    end
  end

  # Staff members are allowed to create assignments.

  # This method is very ugly, and I really should rewrite it. Sorry, future
  # maintainer. :(
  def create
    @assignment = Assignment.find(params[:assignment_id])

    unless current_user.relationship_to_assignment(@assignment) || current_user.is_admin
      flash[:errors] = ["You aren't enrolled in a course with that assignment."]
      redirect_to "/"
      return
    end

    if @assignment.already_due(current_user)
      flash[:errors] = ["Assignment is already due."]
      redirect_to assignment_url(@assignment)
      return
    end

    unless (@assignment.is_visible ||
          current_user.relationship_to_assignment(@assignment) == :staff ||
              current_user.is_admin_or_convener?)
      flash[:errors] = ["Assignment is not visible yet."]
      redirect_to "/"
      return
    end

    @submission = AssignmentSubmission.new(params[:submission])
    @submission.assignment = Assignment.find(params[:assignment_id])
    @submission.user_id = current_user.id
    if @submission.save
      if @assignment.submission_format == "zipfile"
        if (params[:upload] and params[:upload]["datafile"])
          @submission.save_data(params[:upload]["datafile"].read)

          begin
            @submission.zip_contents
          rescue => e
            valid = false
            flash[:errors] = ["That file couldn't be read as a zip file, with
              the following error:", e.to_s]
            render :new
            return
          end

        else
          flash[:errors] = ["Please select a file to upload."]
          render :new
          return
        end
      end

      @submission.make_files
      @submission.receive_submission
      redirect_to(assignment_assignment_submission_url(params[:assignment_id],@submission))
    else
      flash[:errors] = ["Assignment was not successfully saved"] + @submission.errors.full_messages
      render :new
    end
  end

  def destroy
    if current_user.is_admin_or_convener?
      @submission = AssignmentSubmission.find_by_id(params[:id])
      if @submission
        @submission.delete
        flash[:notifications] = ["Assignment submission #{@submission.id} for #{@submission.assignment.name} by #{@submission.user.name} was deleted"]
        redirect_to @submission.assignment
      else
        flash[:errors] = ["That assignment submission could not be found."]
        redirect_to "/"
      end
    else
      flash[:errors] = "You aren't allowed to do that."
      redirect_to @submission.assignment
    end
  end


  def get_zip
    @submission = AssignmentSubmission.find(params[:id])
    assignment = Assignment.find(@submission.assignment_id)

    filename = @submission.pretty_filename(current_user) + '.zip"'

    if @submission.permits?(current_user)
      response.headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
      send_file(@submission.zip_path)
    else
      flash[:errors] = ["You don't have permission to access that page"]
      redirect_to "/"
    end
  end

  def finalize
    @submission = AssignmentSubmission.find(params[:assignment_submission_id])
    @relationship = @submission.relationship_to_user(current_user)
    if @relationship
      @submission.finalize!
      flash[:notifications] = ["Assignment submission finalized."]
      redirect_to :back
    else
      flash[:errors] = ["Permission denied"]
      logger.warn("Security warning: someone tried to finalize someone else's submission")
      redirect_to "/"
    end
  end

  def printable
    @submission = AssignmentSubmission.find(params[:assignment_submission_id])
    relationship = @submission.relationship_to_user(current_user)
    if relationship
      @assignment = @submission.assignment
      html = render :printable, :layout => false
    else
      flash[:errors] = ["Permission denied"]
      logger.warn("Security warning: someone tried to finalize someone else's submission")
      redirect_to "/"
    end
  end

  def pdf
    @submission = AssignmentSubmission.find(params[:assignment_submission_id])
    relationship = @submission.relationship_to_user(current_user)
    if relationship
      send_file(@submission.make_pdf, :type => 'application/pdf')
    else
      flash[:errors] = ["Permission denied"]
      logger.warn("Security warning: someone tried to finalize someone else's submission")
      redirect_to "/"
    end
  end
  
  def download_raw
    @submission = AssignmentSubmission.find(params[:id])
    send_data @submission.body, :filename => "Main.hs", :type => 'application/text'
  end
  
end

app/views/assignment_submissions/_comment.html.erb
<div class="comment">

  <h4>
    <% if comment.user %>
      <%= submission.context_name(comment.user, current_user) %>
    <% else %>
      Automatic comment
    <% end %>
    <% if current_user.is_admin %>
      <small>Comment ID: <%= comment.id %></small>
    <% end %>
  </h4>

  <p>
    <%= sanitize comment.body, tags: %w(li ul ol code strong em b a) %>
  </p>

  <% if comment.has_file %>
    <strong>Attached file:</strong>
    <%= link_to comment.file_name, comment_file_url(comment) %>
  <% end %>

  <% if current_user.is_admin_or_convener? || relationship == :staff %>
      <%= button_to("Delete",assignment_assignment_submission_comment_url(
            @assignment, @submission, comment), :method => :delete,
                  :class => "btn btn-danger btn-sm delete-button") %>
  <% end %>

  <% comment.children.each do |child| %>
    <%= render :partial => "comment", :locals =>
                          { :comment => child,
                            :submission => @submission,
                            :relationship => @relationship,
                            :assignment => @assignment
                            } %>
  <% end %>
  <% if comment.user %>
    <%= render :partial => "new_comment",
             :locals => { :relationship => @relationship,
                          :submission => @submission,
                          :assignment => @assignment,
                          :parent_id => comment.id } %>
  <% end %>
</div>

app/views/assignment_submissions/_file.html.erb
<pre><code class="prettyprint"><% file.body.split("\n").each_with_index do |line, index| %><small><%= (index + 1).to_s.ljust(3) %></small> <span class="line-of-code"><%= line.rstrip.gsub("\t","    ") %></span><br><% end %></code></pre>

app/views/assignment_submissions/_new_comment.html.erb
<h5 data-toggle="collapse" data-target="#comment-<%= parent_id %>">
<% if parent_id.nil? %>
  <button class="btn btn-primary btn-sm">New comment</button>
<% else %>
  <button class="btn btn-primary btn-sm">Reply</button>
<% end %>
</h5>

<div id="comment-<%= parent_id %>" class="collapse comment">
<% if relationship == :peer && submission.which_peer_review_cycle(
                                      current_user).anonymise %>
  <p>This comment is anonymous: the submitter won't know who you are.</p>
<% end %>
  <form method="POST"
        action="<%= assignment_assignment_submission_comments_url(
                  assignment, submission)%>"
        enctype="multipart/form-data"
        role="form"
        class="form"
        >
    <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

    <input type="hidden" name="comment[parent_id]" value="<%= parent_id %>">
    <div class="form-group">
      <textarea name="comment[body]" class="form-control"></textarea>
    </div>

    <% if relationship == :staff || submission.which_peer_review_cycle(
                                      current_user).try(:maximum_mark) %>
      <p data-toggle="collapse" data-target="#marks-<%= parent_id %>">
      <a class="btn btn-success btn-sm">Add mark</a> 
        <% if relationship == :staff %>
          &nbsp; for <%= @submission.user.name %> (u<%=@submission.user.uni_id%>)
        <% end %>
      </p>

      <div id="marks-<%= parent_id %>" class="collapse">
        <% if relationship == :staff %>
          <% assignment.marking_categories.each do |category| %>
            <div class="form-group">
              <%= category.name %> (<%= category.maximum_mark %> marks)
              <input id="mark_<%= category.name %>"
                     name="mark[<%= category.id%>]"
                     class="form-control">
            </div>
          <% end %>
        <% end %>
        <% peer_review_cycle = submission.which_peer_review_cycle(
                                                current_user) %>
        <% if peer_review_cycle && peer_review_cycle.maximum_mark %>
          <div class="form-group">
            Mark (out of <%= peer_review_cycle.maximum_mark %>)
            <input id="peer_mark"
                   name="peer_mark"
                   class="form-control">
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="form-group">
      Attach file: <%= file_field 'upload', 'datafile' %>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" value="Post comment">
    </div>
  </form>
</div>

app/views/assignment_submissions/_new_plaintext.html.erb
<form method="POST"
  action="<%= assignment_assignment_submissions_url(assignment) %>"
    role="form">
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

  <%= sanitize (assignment.submission_instructions || "<p>Please put the text of your submission in here.</p>"), tags: %w(li ul ol code strong em b a) %>

  <textarea name="submission[body]" class="form-control" style="font-family: monospace; height:200px" placeholder="You should put the text of your project into here. This is not a file upload field."><%= submission.body if submission %></textarea>
  <p>You should put the text of your project into here. This is not a file upload field.</p>
  <br>
  <input class="btn btn-primary" type="submit" value="Submit!">
</form>

app/views/assignment_submissions/_new_zipfile.html.erb
<%= sanitize (assignment.submission_instructions || "<p>Please zip your assignment and upload it.</p>
<p>If it's going to be peer reviewed, please don't write your name or uni
id in the source code.</p>"), tags: %w(li ul ol code strong em b a) %>

<form method="POST"
         action="<%= assignment_assignment_submissions_url(assignment) %>"
         enctype="multipart/form-data">
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
  <%= file_field 'upload', 'datafile' %>
  <br>
  <input type="submit" value="Submit!" class="btn btn-primary">
</form>

app/views/assignment_submissions/_plaintext.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Main.hs 
        
        <% unless ((current_user.relationship_to_assignment(@assignment) != :staff) && 
          ((@assignment.courses & current_user.convened_courses).length == 0)) && 
          (!@submission.permitted_users.pluck(:uni_id).include? current_user.uni_id) %>
        
            <%= link_to "Download submission", {:action => "download_raw"}, 
              :class => 'btn btn-primary btn-sm', :style => "float:right; display:block" %> 
          
        <% end %>
        </h4>
      </div>
      <div class="panel-body">
        <%= render :partial => "file", :locals => { :file =>
                              submission.submission_files.first } %>
      </div>
    </div>
  </div>
</div>

app/views/assignment_submissions/_zipfile.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <p><%= link_to "Download submission", assignment_submission_zip_url(submission.assignment_id, submission),
                :class=>"btn btn-default btn-sm" %>
      <%= link_to "View printable code", assignment_assignment_submission_printable_url(submission.assignment_id, submission), :class => "btn btn-default btn-sm" %>
      <%= link_to "Download PDF of assignment", assignment_assignment_submission_pdf_url(submission.assignment_id, submission), :class => "btn btn-default btn-sm" %></p>
    <h3>Files</h3>

      <div class="panel panel-default">
        <div class="panel-heading">
          <p class="panel-title">Files submitted</p>
        </div>
        <div id="list-of-all" class="panel-collapse panel-body">
          <p>If this looks wrong, try resubmitting. In particular, if this is empty, something is wrong.</p>
          <ul>
            <% submission.all_zip_contents(@assignment).each do |filename| %>
              <li><%= filename %></li>
            <% end %>
          </ul>
        </div>
      </div>

  </div>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

    <% submission.submission_files.each do |file| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <p class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#<%= file.name.hash %>">
                <%= file.name %> (<%= file.body.try(:length) || file.file_blob.length/1024 %> KB)
            </a>
          </p>
        </div>
        <% if file.body %>
          <div id="<%= file.name.hash %>" class="panel-collapse panel-body collapse">

            <%= render :partial => "file", :locals => { :file => file } %>
          </div>
        <% else %>
          <div id="<%= file.name.hash %>" class="panel-collapse panel-body collapse">
            <%= link_to "Download file", file_serve_url(file) %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/assignment_submissions/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h3>New assignment submission for
      <%= link_to(@assignment.name, assignment_url(@assignment)) %>
    </h3>

    <% if @assignment.submission_format == "zipfile" %>
      <%= render :partial => "new_zipfile",
          :locals => { :submission => @submission, :assignment => @assignment} %>
    <% elsif @assignment.submission_format == "plaintext" %>
      <%= render :partial => "new_plaintext",
          :locals => { :submission => @submission, :assignment => @assignment} %>
    <% end %>
  </div>
</div>

app/views/assignment_submissions/printable.html.erb
<h1>Submission for <%= @assignment.name %> by <%= @submission.user.name %></h1>


<% @submission.submission_files.each do |file| %>
  <% if file.body %>
    <h4><%= file.name %> (<%= file.body.try(:length) || file.file_blob.length %> bytes)</h4>
    <%= render :partial => "file", :locals => { :file => file } %>
    <hr>
  <% end %>
<% end %>


<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

app/views/assignment_submissions/show.html.erb
<% content_for :title,
    "#{@submission.context_name(@submission.user, current_user)}: #{
    @assignment.name}" %>

<div class="row">
  <div class="col-xs-5 col-xs-offset-2">
    <h2>Submission for <%=  link_to @assignment.name, assignment_url(@assignment) %></h2>
    <p><small>Submitted at <%= @submission.created_at %></small></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% if @submission.permitted_users.include?(current_user) %>
      <h3><%= @submission.context_name(@submission.user, current_user) %></h3>
    <% elsif current_user == @submission.user %>
      <% unless @assignment.already_due(current_user) %>
        <p>
        <%= link_to "Submit new version", new_assignment_assignment_submission_url(
                            @assignment), :class => "btn btn-primary btn-sm"%>
          <% if current_user.is_admin_or_convener? %>
          <%= link_to("Delete submission",
                assignment_assignment_submission_url(@assignment, @submission),
                :method => :delete,
                :class => "btn btn-danger btn-sm", :style => "float:right") %>
        <% end %>
        <% else %>
          <h3> <%= link_to(@submission.user.name,user_url(@submission.user)) %>
            (u<%= @submission.user.uni_id%>)
          </h3>
        <% end %>
        </p>
      <% end %>

    <% if @relationship == :staff && @submission.permitted_users.count > 0%>
      <p>This submission is visible to: <%=@submission.permitted_users.map {|u|
             link_to(u.name, u)}.join(", ").html_safe %></p>
    <% end %>

    <%# Only the submitter and staff should be able to click on Finalize. Luckily, they're also the only ones who can see the assignment before it's finalized. %>

    <% unless @submission.is_finalized %>
    <div class="alert alert-warning" style="margin-top:10px; padding-bottom:60px">
      <h4>  <span class="glyphicon glyphicon-warning-sign"></span> Not finalized</h4><%= button_to "Finalize", assignment_assignment_submission_finalize_url(
            @assignment, @submission), :class => "btn btn-primary pull-right" %>
      <p>This submission has not been finalized. It will not be submitted for tutor consideration or peer review until you finalize it.</p>
    </div>
    <% end %>
  </div>
</div>

<% if @assignment.visible_comments || current_user != @submission.user %>
  <div class="row">
    <div class="col-xs-5 col-xs-offset-2">
      <% @assignment.marking_categories.each do |category| %>
        <p><%= category.name %>: <%= category.mark_for_submission(@submission) || "-"%>/<%= category.maximum_mark %></p>
      <% end %>
      <% @assignment.peer_review_cycles.each do |cycle| %>
        <% next unless cycle.maximum_mark %>
        <p>Peer review mark for cycle <%= cycle.id %>:
            <%= cycle.mark_for_submission(@submission) || "-"%>/<%=
                                                          cycle.maximum_mark %>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

<% if @assignment.submission_format == "plaintext" %>
  <%= render :partial => "plaintext",
                      :locals => { :submission => @submission} %>
<% elsif @assignment.submission_format == "zipfile" %>
  <%= render :partial => "zipfile",
                      :locals => { :submission => @submission} %>
<% end %>

<% if @assignment.visible_comments || current_user != @submission.user %>
  <div class="row">
    <div class="col-xs-5 col-xs-offset-2">
      <h3>Comments</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">

      <div id="comments">
        <% @submission.top_level_comments.each do |comment| %>
          <%= render :partial => "comment", :locals =>
                            { :comment => comment,
                              :submission => @submission,
                              :relationship => @relationship,
                              :assignment => @assignment
                              } %>
        <% end %>

        <%= render :partial => "new_comment",
            :locals => { :relationship => @relationship,
                         :submission => @submission,
                         :assignment => @assignment,
                         :parent_id => nil } %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <p>Comments have been disabled while the assignment is marked.</p>
    </div>
  </div>
<% end %>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>