config/routes.rb
SubmissionApp::Application.routes.draw do
  # get "groups/show"

  # get "group/show"

  resource :sessions, :only => [:new, :create, :destroy]

  resources :courses, :only => [:new, :create, :index, :show, :destroy] do
    resources :users, :only => [:new, :create]
    resources :student_enrollments, :only => [:create, :destroy]
  end

  resources :users, :only => [:show, :index, :destroy]

  resources :group_types do
    resources :assignments, :only => [:new]
    resources :groups, :only => [:create]
    post 'csv', :to => 'group_types#edit_by_csv', :as => 'edit_by_csv'
  end

  resources :groups, :only => [:show]

  resources :assignments, :only => [:show, :create, :destroy, :edit, :update] do
    resources :assignment_submissions, :except => [:update, :edit] do
      resources :comments, :only => [:create, :destroy]
      post 'finalize', :to => 'assignment_submissions#finalize',
                       :as => "finalize"
      get 'printable', :to => 'assignment_submissions#printable',
                        :as => "printable"
      get 'pdf', :to => 'assignment_submissions#pdf',
                 :as => 'pdf'
    end

    get 'groups/:id', :to => 'groups#assignment_show', :as => 'group_show'
    get 'groups/:id/zip', :to => 'groups#assignment_zip', :as => 'group_zip'


    get 'cycles', :to => 'peer_review_cycles#index', :as => "cycles"
    post 'cycles', :to => 'peer_review_cycles#create'
    put 'cycles/:id/edit', :to => 'peer_review_cycles#update'
    delete 'cycles/:id', :to => 'peer_review_cycles#delete', :as => "cycles_delete"
    get 'cycles/:id/edit', :to => 'peer_review_cycles#edit', :as => "cycles_edit"
    post 'cycles/:id/activate', :to => 'peer_review_cycles#activate',
                                :as => "cycle_activate"
    post 'cycles/:id/deactivate', :to => 'peer_review_cycles#deactivate',
                                :as => "cycle_deactivate"

    resources :marking_categories, :only => [:create, :destroy, :update, :index]
    resources :custom_behaviors, :only => [:create, :destroy, :update, :index]

    resources :extensions, :only => [:index, :create]
  end

  resources :extensions, :only => [:destroy]

  resources :notifications, :only => [:destroy, :index]

  get 'assignments/:id/marks.csv', :to => 'assignments#get_csv',
                                   :as => 'assignment_marks'

  get 'assignments/:id/submissions.zip', :to => 'assignments#get_zipfile',
                                         :as => 'assignment_zipfile'

  post 'assignments/:id/peer_review', :to => 'assignments#peer_review',
                                      :as => 'assignment_peer_review'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/file.zip',
                                    :to => 'assignment_submissions#get_zip',
                                    :as => 'assignment_submission_zip'
  
  get 'assignments/:assignment_id/assignment_submissions/:id/Main.hs',
                                    :to => 'assignment_submissions#download_raw',
                                    :as => 'assignment_submission_raw'

  get 'comment_files/:id', :to => 'comments#get_file',
                           :as => 'comment_file'

  root :to => 'courses#index'

  get 'admin/log', :to => 'admin#log'
  get 'admin/summary_log', :to => 'admin#summary_log'
  get 'admin/database', :to => 'admin#database'
  get 'admin/spoof-login/:id', :to => 'admin#spoof_login'
  get 'admin/charts', :to => 'admin#charts'

  get 'files/:id', :to => 'submission_files#serve', :as => 'file_serve'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :require_logged_in, :except => [:index]
  before_filter :require_convener_or_admin, :except => [:show, :index]

  def new
    @course = Course.new
    render :new
  end

  def create
    @course = Course.new(params[:course])
    unless current_user.is_admin
      @course.convener = current_user
    end

    ActiveRecord::Base.transaction do
      @course.save!
      @course.add_students_by_csv(params[:students_csv])
      flash[:notifications] =
            ["Course #{@course.name} created with #{@course.students.length} students."]
      redirect_to @course
    end
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.nil?
      flash[:errors] = ["The course you just tried to delete doesn't exist."]
    elsif @course.admin_or_convener?(current_user)
      @course.destroy
      flash[:notifications] = ["Course #{@course.name} destroyed."]
      redirect_to courses_url
    else
      flash[:errors] = ["You can't delete that course, and you shouldn't have that url..."]
      redirect_to course_url(@course)
    end
  end

  def index
    if current_user
      @user_courses = current_user.courses
      @other_courses = Course.all - @user_courses
      render :index
    else
      redirect_to new_sessions_url
    end
  end

  def show
    @course = Course.find(params[:id])

    if @course.nil?
      flash[:errors] = ["Looks like you went looking for a course that doesn't exist."]
    end

    @convener = @course.convener
    @staffs = @course.staff # Yes, I am aware that the plural of staff isn't staffs
    if current_user.courses.include?(@course) || current_user.is_admin
      @students = @course.students
      @group_types = @course.group_types
      @assignments = @course.assignments.visible.order("due_date ASC")
    end

    render :show
  end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-offset-2">
    <h2>Courses</h2>

    <% if current_user.is_admin_or_convener? %>
      <%= link_to("Create course", new_course_url, :class => "btn btn-primary btn-sm") %>
    <% end %>

    <h3>Your courses</h3>

    <ul>
      <% @user_courses.each do |course| %>
        <li>
          <%= link_to course.name, course_url(course) %>
          (<%= course.convener.name %>)
        </li>
      <% end %>
    </ul>

    <% if current_user.is_admin %>

      <h3>Other courses</h3>
      <ul>
        <% @other_courses.each do |course| %>
          <li>
            <%= link_to course.name, course_url(course) %>
            (<%= course.convener.name %>)
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

    <h2>New course</h2>
  <%= form_for @course, url: {action: "create"}, html: {role: "form"} do |f| %>
    <p><%= label_tag(:name, "Name") %>
    <%= f.text_field(:name) %></p>

    <% if current_user.is_admin %>
      <p><%= label_tag(:convener_id, "Convenor") %>
      <%= f.collection_select(:convener_id, User.all, :id, :name) %></p>
    <% else %>
      <p><strong>Convenor:</strong> <%= current_user.name %> </p>
    <% end %>

    <p><label for="students_csv">Students</label>
      <textarea id="students_csv" name="students_csv">name,uni id</textarea>
    </p>


    <p><%= f.submit("Create course", :class => "btn btn-primary") %></p>
  <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<% content_for :title, @course.name %>

<div class="row">
  <div class="col-sm-9 col-sm-offset-2">
    <h2><%= @course.name %></h2>

    <p><em>Course convener: <%= link_to @convener.name, user_url(@convener) %></em></p>

    <p>
    <% if current_user == @convener || current_user.is_admin %>
      <%= link_to "Create new group type", new_group_type_url , :class => "btn btn-primary btn-sm" %>
      <%= link_to("Enroll students and staff", new_course_user_url(@course), :class => "btn btn-primary btn-sm") %>
    </p>
    <% end %>

    <% if @assignments %>
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Assignments</h4></div>
        <ul class="list-group">
          <% @assignments.each do |assignment| %>
            <li class="list-group-item">
              <%= link_to assignment.name, assignment_url(assignment) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <% if @group_types %>
      <% @group_types.each do |group_type| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4><%= link_to group_type.name, group_type_url(group_type) %>
              <% if current_user == @convener %>
                <div class="btn-group" style="float:right">
                <%= link_to "New assignment", new_group_type_assignment_url(group_type), 
                  :class => "btn btn-default btn-sm" %>
                <%= link_to "Delete group", group_type_url(group_type), :method => :delete, 
                  :class => "btn btn-danger btn-sm", data: {confirm: "Are you sure?"} %>
                </div>
              <% end %>
            </h4>
          </div>

          <ul class="list-group">
            <% group_type.groups.each do |group| %>
              <li class="list-group-item">
                <%= link_to group.name, group_url(group) %>
              </li>
            <% end %>
          </ul>
        </div>
    
      <% end %>
    <% end %>

    <h3>Staff</h3>
    <table id="staff" class="table table-bordered table-striped">
      <% @staffs.each do |staff| %>
      <tr>
        <td> <%= link_to staff.name, user_url(staff) %> </td>
      </tr>
      <% end %>
    </table>

    <% if (@course.staff+[@course.convener]).include?(current_user) or current_user.is_admin %>
      <h3>Students</h3>
      <table id="students" class="table table-bordered table-striped">
        <tr>
          <th><h5>Student</h5></th>
          <th><h5>ID</h5></th>
        </tr>
        <% @students.each do |student| %>
            <tr>
              <!-- User info -->
              <td><%= link_to student.name, user_url(student) %></td>
              <td><%= link_to "u" + student.uni_id.to_s, user_url(student) %></td>
            </tr>
        <% end %>
      </table>
    
    <% elsif @course.students.include? current_user %>
    <% else %>
      <em>Note that you aren't enrolled in this course--you'd
             see more if you were.</em>
    <% end %>
  </div>
</div>